In [68]:
import tensorflow as tf
import pickle
import pandas as pd
import numpy as np

In [69]:
data = pd.read_csv("Churn_Modelling.csv")

In [70]:
data = data.drop(["RowNumber", "CustomerId", "Surname"], axis=1)

In [71]:
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [72]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
data["Gender"] = lb.fit_transform(data["Gender"])

In [73]:
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [74]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()
geo_encoded = ohe.fit_transform(data[["Geography"]]).toarray()

In [75]:
ohe.get_feature_names_out()

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [76]:
geo_encoded_df = pd.DataFrame(data=geo_encoded, columns=ohe.get_feature_names_out())

In [77]:
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [78]:
data = pd.concat([data.drop("Geography", axis=1), geo_encoded_df], axis=1)

In [79]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [80]:
# Split the data into features and target
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [82]:
## Split the data in training and tetsing sets
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [84]:
## Scale these features
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

#### ANN Regression Problem statement

In [85]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [87]:
# Build the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer for regression # No need of specifying activation function in regression ps
])

## compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 64)                832

 dense_4 (Dense)             (None, 32)                2080

 dense_5 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [88]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [89]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [90]:
# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
WARNING:tensorflow:From d:\AIML Material\venv\lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From d:\AIML Material\venv\lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 3s 5ms/step - loss: 100399.0312 - mae: 100399.0312 - val_loss: 98594.1250 - val_mae: 98594.1250
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 99897.3594 - mae: 99897.3594 - val_loss: 97560.5625 - val_mae: 97560.5625
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 98068.7891 - mae: 98068.7891 - val_loss: 94840.5078 - val_mae: 94840.5078
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 94363.6562 - mae: 94363.6562 - val_loss: 90141.2812 - val_mae: 90141.2812
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 88721.4141 - mae: 88721.4141 - val_loss: 83706.8906 - val_mae: 83706.8906
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 81538.8750 - mae: 81538.8750 - val_loss: 76185.7656 - val_mae: 76185.7656
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 73744.4062 - mae: 73744.4062 - val_loss: 68723.5312 - val_mae: 68723.5312
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 66298.0625 - mae: 66298.0625 - val_loss: 62208.5469 - val_mae: 62208.5469
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 60098.7422 - mae: 60098.7422 - val_loss: 57125.2109 - val_mae: 57125.2109
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 55622.2266 - mae: 55622.2266 - val_loss: 53834.1641 - val_mae: 53834.1641
Epoch 11/100
250/250 [==============================] - 1s 4ms/step - loss: 52809.0156 - mae: 52809.0156 - val_loss: 52071.0000 - val_mae: 52071.0000
Epoch 12/100
250/250 [==============================] - 1s 4ms/step - loss: 51361.1562 - mae: 51361.1562 - val_loss: 51346.1523 - val_mae: 51346.1523
Epoch 13/100
250/250 [==============================] - 1s 5ms/step - loss: 50741.6211 - mae: 50741.6211 - val_loss: 51073.8555 - val_mae: 51073.8555
Epoch 14/100
250/250 [==============================] - 1s 4ms/step - loss: 50458.8047 - mae: 50458.8047 - val_loss: 50959.9219 - val_mae: 50959.9219
Epoch 15/100
250/250 [==============================] - 1s 3ms/step - loss: 50321.7227 - mae: 50321.7227 - val_loss: 50917.5312 - val_mae: 50917.5312
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 50244.6680 - mae: 50244.6680 - val_loss: 50877.1172 - val_mae: 50877.1172
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 50186.6445 - mae: 50186.6445 - val_loss: 50839.1719 - val_mae: 50839.1719
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 50136.6094 - mae: 50136.6094 - val_loss: 50806.7422 - val_mae: 50806.7422
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 50093.7344 - mae: 50093.7344 - val_loss: 50775.2109 - val_mae: 50775.2109
Epoch 20/100
250/250 [==============================] - 1s 4ms/step - loss: 50052.9883 - mae: 50052.9883 - val_loss: 50741.9141 - val_mae: 50741.9141
Epoch 21/100
250/250 [==============================] - 1s 4ms/step - loss: 50018.5781 - mae: 50018.5781 - val_loss: 50718.5586 - val_mae: 50718.5586
Epoch 22/100
250/250 [==============================] - 1s 3ms/step - loss: 49984.8984 - mae: 49984.8984 - val_loss: 50695.2891 - val_mae: 50695.2891
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 49954.8477 - mae: 49954.8477 - val_loss: 50661.5195 - val_mae: 50661.5195
Epoch 24/100
250/250 [==============================] - 1s 3ms/step - loss: 49925.1953 - mae: 49925.1953 - val_loss: 50634.8945 - val_mae: 50634.8945
Epoch 25/100
250/250 [==============================] - 1s 4ms/step - loss: 49899.5430 - mae: 49899.5430 - val_loss: 50611.2305 - val_mae: 50611.2305
Epoch 26/100
250/250 [==============================] - 1s 5ms/step - loss: 49874.3086 - mae: 49874.3086 - val_loss: 50591.3672 - val_mae: 50591.3672
Epoch 27/100
250/250 [==============================] - 1s 3ms/step - loss: 49851.4062 - mae: 49851.4062 - val_loss: 50571.6562 - val_mae: 50571.6562
Epoch 28/100
250/250 [==============================] - 1s 2ms/step - loss: 49830.7422 - mae: 49830.7422 - val_loss: 50543.5547 - val_mae: 50543.5547
Epoch 29/100
250/250 [==============================] - 1s 2ms/step - loss: 49814.1523 - mae: 49814.1523 - val_loss: 50525.9414 - val_mae: 50525.9414
Epoch 30/100
250/250 [==============================] - 1s 2ms/step - loss: 49794.3828 - mae: 49794.3828 - val_loss: 50511.4805 - val_mae: 50511.4805
Epoch 31/100
250/250 [==============================] - 1s 2ms/step - loss: 49777.6328 - mae: 49777.6328 - val_loss: 50492.1914 - val_mae: 50492.1914
Epoch 32/100
250/250 [==============================] - 1s 2ms/step - loss: 49758.5703 - mae: 49758.5703 - val_loss: 50476.4609 - val_mae: 50476.4609
Epoch 33/100
250/250 [==============================] - 1s 3ms/step - loss: 49744.6914 - mae: 49744.6914 - val_loss: 50458.2227 - val_mae: 50458.2227
Epoch 34/100
250/250 [==============================] - 1s 2ms/step - loss: 49731.2891 - mae: 49731.2891 - val_loss: 50443.1172 - val_mae: 50443.1172
Epoch 35/100
250/250 [==============================] - 1s 2ms/step - loss: 49716.2734 - mae: 49716.2734 - val_loss: 50437.7852 - val_mae: 50437.7852
Epoch 36/100
250/250 [==============================] - 1s 3ms/step - loss: 49703.9609 - mae: 49703.9609 - val_loss: 50422.8164 - val_mae: 50422.8164
Epoch 37/100
250/250 [==============================] - 1s 3ms/step - loss: 49688.6211 - mae: 49688.6211 - val_loss: 50417.6523 - val_mae: 50417.6523
Epoch 38/100
250/250 [==============================] - 1s 2ms/step - loss: 49679.3633 - mae: 49679.3633 - val_loss: 50412.6211 - val_mae: 50412.6211
Epoch 39/100
250/250 [==============================] - 1s 2ms/step - loss: 49668.5312 - mae: 49668.5312 - val_loss: 50396.1875 - val_mae: 50396.1875
Epoch 40/100
250/250 [==============================] - 1s 2ms/step - loss: 49654.8398 - mae: 49654.8398 - val_loss: 50387.5859 - val_mae: 50387.5859
Epoch 41/100
250/250 [==============================] - 1s 2ms/step - loss: 49649.9688 - mae: 49649.9688 - val_loss: 50383.8008 - val_mae: 50383.8008
Epoch 42/100
250/250 [==============================] - 1s 2ms/step - loss: 49635.5352 - mae: 49635.5352 - val_loss: 50376.7227 - val_mae: 50376.7227
Epoch 43/100
250/250 [==============================] - 1s 3ms/step - loss: 49627.4844 - mae: 49627.4844 - val_loss: 50368.3242 - val_mae: 50368.3242
Epoch 44/100
250/250 [==============================] - 1s 3ms/step - loss: 49620.1523 - mae: 49620.1523 - val_loss: 50355.5586 - val_mae: 50355.5586
Epoch 45/100
250/250 [==============================] - 1s 3ms/step - loss: 49610.2539 - mae: 49610.2539 - val_loss: 50352.5469 - val_mae: 50352.5469
Epoch 46/100
250/250 [==============================] - 1s 3ms/step - loss: 49600.4375 - mae: 49600.4375 - val_loss: 50352.6914 - val_mae: 50352.6914
Epoch 47/100
250/250 [==============================] - 1s 2ms/step - loss: 49594.6406 - mae: 49594.6406 - val_loss: 50357.7695 - val_mae: 50357.7695
Epoch 48/100
250/250 [==============================] - 1s 2ms/step - loss: 49586.6289 - mae: 49586.6289 - val_loss: 50357.1797 - val_mae: 50357.1797
Epoch 49/100
250/250 [==============================] - 1s 2ms/step - loss: 49576.9219 - mae: 49576.9219 - val_loss: 50353.3594 - val_mae: 50353.3594
Epoch 50/100
250/250 [==============================] - 1s 3ms/step - loss: 49570.8359 - mae: 49570.8359 - val_loss: 50347.8008 - val_mae: 50347.8008
Epoch 51/100
250/250 [==============================] - 1s 3ms/step - loss: 49563.3242 - mae: 49563.3242 - val_loss: 50348.4414 - val_mae: 50348.4414
Epoch 52/100
250/250 [==============================] - 1s 4ms/step - loss: 49556.8242 - mae: 49556.8242 - val_loss: 50340.5625 - val_mae: 50340.5625
Epoch 53/100
250/250 [==============================] - 1s 3ms/step - loss: 49549.1875 - mae: 49549.1875 - val_loss: 50347.7148 - val_mae: 50347.7148
Epoch 54/100
250/250 [==============================] - 1s 3ms/step - loss: 49543.9102 - mae: 49543.9102 - val_loss: 50340.3945 - val_mae: 50340.3945
Epoch 55/100
250/250 [==============================] - 1s 3ms/step - loss: 49536.6172 - mae: 49536.6172 - val_loss: 50337.2578 - val_mae: 50337.2578
Epoch 56/100
250/250 [==============================] - 1s 6ms/step - loss: 49530.2461 - mae: 49530.2461 - val_loss: 50340.6133 - val_mae: 50340.6133
Epoch 57/100
250/250 [==============================] - 1s 4ms/step - loss: 49525.1016 - mae: 49525.1016 - val_loss: 50329.0977 - val_mae: 50329.0977
Epoch 58/100
250/250 [==============================] - 1s 4ms/step - loss: 49520.7344 - mae: 49520.7344 - val_loss: 50327.5508 - val_mae: 50327.5508
Epoch 59/100
250/250 [==============================] - 1s 3ms/step - loss: 49514.8477 - mae: 49514.8477 - val_loss: 50328.4648 - val_mae: 50328.4648
Epoch 60/100
250/250 [==============================] - 1s 3ms/step - loss: 49508.8281 - mae: 49508.8281 - val_loss: 50318.5039 - val_mae: 50318.5039
Epoch 61/100
250/250 [==============================] - 1s 3ms/step - loss: 49505.4727 - mae: 49505.4727 - val_loss: 50322.2266 - val_mae: 50322.2266
Epoch 62/100
250/250 [==============================] - 1s 3ms/step - loss: 49499.5898 - mae: 49499.5898 - val_loss: 50323.2031 - val_mae: 50323.2031
Epoch 63/100
250/250 [==============================] - 1s 3ms/step - loss: 49493.1172 - mae: 49493.1172 - val_loss: 50317.2656 - val_mae: 50317.2656
Epoch 64/100
250/250 [==============================] - 1s 3ms/step - loss: 49490.5195 - mae: 49490.5195 - val_loss: 50313.7188 - val_mae: 50313.7188
Epoch 65/100
250/250 [==============================] - 1s 3ms/step - loss: 49483.3359 - mae: 49483.3359 - val_loss: 50305.1094 - val_mae: 50305.1094
Epoch 66/100
250/250 [==============================] - 1s 4ms/step - loss: 49478.4453 - mae: 49478.4453 - val_loss: 50313.0742 - val_mae: 50313.0742
Epoch 67/100
250/250 [==============================] - 1s 3ms/step - loss: 49473.8086 - mae: 49473.8086 - val_loss: 50320.5430 - val_mae: 50320.5430
Epoch 68/100
250/250 [==============================] - 1s 3ms/step - loss: 49468.3672 - mae: 49468.3672 - val_loss: 50308.2852 - val_mae: 50308.2852
Epoch 69/100
250/250 [==============================] - 1s 3ms/step - loss: 49464.8867 - mae: 49464.8867 - val_loss: 50308.1992 - val_mae: 50308.1992
Epoch 70/100
250/250 [==============================] - 1s 3ms/step - loss: 49461.2617 - mae: 49461.2617 - val_loss: 50309.1016 - val_mae: 50309.1016
Epoch 71/100
250/250 [==============================] - 1s 3ms/step - loss: 49454.4492 - mae: 49454.4492 - val_loss: 50302.9297 - val_mae: 50302.9297
Epoch 72/100
250/250 [==============================] - 1s 4ms/step - loss: 49450.4648 - mae: 49450.4648 - val_loss: 50298.1094 - val_mae: 50298.1094
Epoch 73/100
250/250 [==============================] - 1s 3ms/step - loss: 49444.3477 - mae: 49444.3477 - val_loss: 50301.5391 - val_mae: 50301.5391
Epoch 74/100
250/250 [==============================] - 1s 3ms/step - loss: 49443.1094 - mae: 49443.1094 - val_loss: 50306.7656 - val_mae: 50306.7656
Epoch 75/100
250/250 [==============================] - 1s 4ms/step - loss: 49440.1758 - mae: 49440.1758 - val_loss: 50288.8789 - val_mae: 50288.8789
Epoch 76/100
250/250 [==============================] - 1s 4ms/step - loss: 49435.4609 - mae: 49435.4609 - val_loss: 50302.1797 - val_mae: 50302.1797
Epoch 77/100
250/250 [==============================] - 1s 4ms/step - loss: 49432.3086 - mae: 49432.3086 - val_loss: 50299.6680 - val_mae: 50299.6680
Epoch 78/100
250/250 [==============================] - 1s 3ms/step - loss: 49428.5000 - mae: 49428.5000 - val_loss: 50304.3008 - val_mae: 50304.3008
Epoch 79/100
250/250 [==============================] - 1s 3ms/step - loss: 49424.3281 - mae: 49424.3281 - val_loss: 50298.4375 - val_mae: 50298.4375
Epoch 80/100
250/250 [==============================] - 1s 4ms/step - loss: 49419.8867 - mae: 49419.8867 - val_loss: 50305.6562 - val_mae: 50305.6562
Epoch 81/100
250/250 [==============================] - 1s 4ms/step - loss: 49418.4414 - mae: 49418.4414 - val_loss: 50311.0938 - val_mae: 50311.0938
Epoch 82/100
250/250 [==============================] - 1s 4ms/step - loss: 49414.3281 - mae: 49414.3281 - val_loss: 50298.5586 - val_mae: 50298.5586
Epoch 83/100
250/250 [==============================] - 1s 4ms/step - loss: 49411.6016 - mae: 49411.6016 - val_loss: 50299.2031 - val_mae: 50299.2031
Epoch 84/100
250/250 [==============================] - 1s 4ms/step - loss: 49407.0664 - mae: 49407.0664 - val_loss: 50320.2148 - val_mae: 50320.2148
Epoch 85/100
250/250 [==============================] - 1s 4ms/step - loss: 49404.1875 - mae: 49404.1875 - val_loss: 50311.4141 - val_mae: 50311.4141

In [91]:
%load_ext tensorboard

In [92]:
%tensorboard --logdir regressionlogs/fit